"""empty message

Revision ID: 1d717c4ec5cc
Revises: 359344e43faf
Create Date: 2023-06-07 13:52:04.034274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d717c4ec5cc'
down_revision = '359344e43faf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('make_model', sa.String(length=150), nullable=True),
    sa.Column('description', sa.String(length=200), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('max_speed', sa.String(length=100), nullable=True),
    sa.Column('fuel_type', sa.String(length=150), nullable=True),
    sa.Column('title', sa.String(length=150), nullable=True),
    sa.Column('accidents', sa.Numeric(precision=5, scale=0), nullable=True),
    sa.Column('mileage', sa.Numeric(precision=8, scale=0), nullable=True),
    sa.Column('location', sa.String(length=150), nullable=True),
    sa.Column('user_token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['user_token'], ['user.token'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('car')
    # ### end Alembic commands ###
